In [76]:
import os
import csv
import pandas as pd
import numpy as np
#load datasets

airbnb = pd.read_csv('AB_NYC_2019.csv')
crime = pd.read_csv('NYC_crime.csv')

C:\Users\anais\AppData\Local\Temp\ipykernel_14520\3969291156.py:7: DtypeWarning: Columns (61,62,94,95) have mixed types. Specify dtype option on import or set low_memory=False.
  airbnb = pd.read_csv('AB_NYC_2019.csv')

In [77]:
#Visualize data
print(airbnb)
print(crime)

             id                            listing_url       scrape_id  \
0          2595      https://www.airbnb.com/rooms/2595  20190806030549
1          3647      https://www.airbnb.com/rooms/3647  20190806030549
2          3831      https://www.airbnb.com/rooms/3831  20190806030549
3          5022      https://www.airbnb.com/rooms/5022  20190806030549
4          5099      https://www.airbnb.com/rooms/5099  20190806030549
...         ...                                    ...             ...
48859  37497806  https://www.airbnb.com/rooms/37497806  20190806030549
48860  37497989  https://www.airbnb.com/rooms/37497989  20190806030549
48861  37498824  https://www.airbnb.com/rooms/37498824  20190806030549
48862  37499051  https://www.airbnb.com/rooms/37499051  20190806030549
48863  37499093  https://www.airbnb.com/rooms/37499093  20190806030549

      last_scraped                                               name  \
0       2019-08-07                              Skylit Midtown Castle
1       2019-08-06                THE VILLAGE OF HARLEM....NEW YORK !
2       2019-08-06                    Cozy Entire Floor of Brownstone
3       2019-08-06   Entire Apt: Spacious Studio/Loft by central park
4       2019-08-06          Large Cozy 1 BR Apartment In Midtown East
...            ...                                                ...
48859   2019-08-06                            Overnighter / Weekender
48860   2019-08-06                     East Harlem's Best Kept Secret
48861   2019-08-06  Perfect, Brand New 1 Bedroom Apartment In Midtown
48862   2019-08-06                Large bedroom overlooking Riverside
48863   2019-08-06  Brand New Spacious 1 Bedroom Apt In Hells Kitchen

                                                 summary  \
0      Find your romantic getaway to this beautiful, ...
1                                                    NaN
2      Urban retreat: enjoy 500 s.f. floor in 1899 br...
3                                                    NaN
4      My large 1 bedroom apartment is true New York ...
...                                                  ...
48859  Cozy apt for short stay guests visiting our be...
48860  Large, comfortable private bedroom in a spacio...
48861  The apartment is right off of 8th Avenue near ...
48862  Bright, calm, and spacious, my place is conven...
48863  Incredibly Stunning & Spacious 800+ sq foot 1 ...

                                                   space  \
0      - Spacious (500+ft²), immaculate and nicely fu...
1      WELCOME TO OUR INTERNATIONAL URBAN COMMUNITY T...
2      Greetings!      We own a double-duplex brownst...
3      Loft apartment with high ceiling and wood floo...
4      I have a large 1 bedroom apartment centrally l...
...                                                  ...
48859  Small back porch overlooking Triborough Bridge...
48860  Your fully furnished room features a full size...
48861  Before submitting a reservation requests (by c...
48862  The room to rent is a very large private room ...
48863  Before submitting a reservation requests (by c...

                                             description experiences_offered  \
0      Find your romantic getaway to this beautiful, ...                none
1      WELCOME TO OUR INTERNATIONAL URBAN COMMUNITY T...                none
2      Urban retreat: enjoy 500 s.f. floor in 1899 br...                none
3      Loft apartment with high ceiling and wood floo...                none
4      My large 1 bedroom apartment is true New York ...                none
...                                                  ...                 ...
48859  Cozy apt for short stay guests visiting our be...                none
48860  Large, comfortable private bedroom in a spacio...                none
48861  The apartment is right off of 8th Avenue near ...                none
48862  Bright, calm, and spacious, my place is conven...                none
48863  Incredibly Stunning & Spacious 800+ sq foot 1 ...                none

                                   neighborhood_overview  ...  \
0      Centrally located in the heart of Manhattan ju...  ...
1                                                    NaN  ...
2      Just the right mix of urban center and local n...  ...
3                                                    NaN  ...
4      My neighborhood in Midtown East is called Murr...  ...
...                                                  ...  ...
48859  Tons of multi cultural cuisine restaurants and...  ...
48860  In the heart of East Harlem I am in between th...  ...
48861  • 5 blocks from Times Square (5 min walk) • 1 ...  ...
48862  Morningside Heights is a vibrant neighbourhood...  ...
48863  • 3 blocks from Times Square (5 min walk) • 1 ...  ...

      instant_bookable is_business_travel_ready          cancellation_policy  \
0                    f                        f  strict_14_with_grace_period
1                    f                        f  strict_14_with_grace_period
2                    f                        f                     moderate
3                    f                        f  strict_14_with_grace_period
4                    f                        f  strict_14_with_grace_period
...                ...                      ...                          ...
48859                f                        f                     flexible
48860                f                        f                     flexible
48861                f                        f  strict_14_with_grace_period
48862                f                        f  strict_14_with_grace_period
48863                f                        f  strict_14_with_grace_period

      require_guest_profile_picture require_guest_phone_verification  \
0                                 t                                t
1                                 t                                t
2                                 f                                f
3                                 t                                t
4                                 t                                t
...                             ...                              ...
48859                             f                                f
48860                             f                                f
48861                             f                                f
48862                             f                                f
48863                             f                                f

       calculated_host_listings_count  \
0                                   2
1                                   1
2                                   1
3                                   1
4                                   1
...                               ...
48859                               1
48860                               1
48861                               1
48862                               1
48863                               1

       calculated_host_listings_count_entire_homes  \
0                                                1
1                                                0
2                                                1
3                                                1
4                                                1
...                                            ...
48859                                            0
48860                                            0
48861                                            1
48862                                            0
48863                                            1

      calculated_host_listings_count_private_rooms  \
0                                                0
1                                                1
2                                                0
3                                                0
4                                                0
...                                            ...
48859                                            0
48860                                            1
48861                                            0
48862                                            1
48863                                            0

       calculated_host_listings_count_shared_rooms  reviews_per_month
0                                                1               0.39
1                                                0                NaN
2                                                0               4.64
3                                                0               0.10
4                                                0               0.60
...                                            ...                ...
48859                                            1                NaN
48860                                            0                NaN
48861                                            0                NaN
48862                                            0                NaN
48863                                            0                NaN

[48864 rows x 106 columns]
         Unnamed: 0  arrest_key arrest_date  \
0                 0   192799737  2019-01-26
1                 1   193260691  2019-02-06
2                 2   149117452  2016-01-06
3                 3   190049060  2018-11-15
4                 4    24288194  2006-09-13
...             ...         ...         ...
3881984     3881984    24592084  2006-10-01
3881985     3881985    24028282  2006-08-25
3881986     3881986    24036787  2006-08-26
3881987     3881987    24028407  2006-08-25
3881988     3881988    24321597  2006-09-14

                                            pd_desc  \
0                                      SEXUAL ABUSE
1           CRIMINAL SALE OF A CONTROLLED SUBSTANCE
2                                            RAPE 3
3                                            RAPE 1
4                              TRESPASS 3, CRIMINAL
...                                             ...
3881984  LARCENY,GRAND FROM OPEN AREAS,UNCLASSIFIED
3881985                       MARIJUANA, SALE 4 & 5
3881986    PUBLIC ADMINISTATION,UNCLASS MISDEMEAN 4
3881987            TRAFFIC,UNCLASSIFIED MISDEMEANOR
3881988          CONTROLLED SUBSTANCE, POSSESSION 7

                                      ofns_desc    law_code law_cat_cd  \
0                                    SEX CRIMES  PL 1306503          F
1                CONTROLLED SUBSTANCES OFFENSES  PL 2203400          F
2                                          RAPE  PL 1302503          F
3                                          RAPE  PL 1303501          F
4                             CRIMINAL TRESPASS  PL 140100E          M
...                                         ...         ...        ...
3881984                           GRAND LARCENY  PL 1553001          F
3881985                         DANGEROUS DRUGS  PL 2214000          M
3881986  OFFENSES AGAINST PUBLIC ADMINISTRATION  PL 1950500          M
3881987                VEHICLE AND TRAFFIC LAWS  VTL05110E2          F
3881988                         DANGEROUS DRUGS  PL 2200300          M

        age_group perp_sex perp_race   latitude  longitude arrest_boro  \
0           45-64        M     BLACK  40.800694 -73.941109           M
1           25-44        M   UNKNOWN  40.757839 -73.991212           M
2           25-44        M     BLACK  40.648650 -73.950336           K
3           25-44        M     BLACK  40.674583 -73.930222           K
4           45-64        M     BLACK  40.671254 -73.926714           K
...           ...      ...       ...        ...        ...         ...
3881984       <18        M     BLACK  40.676655 -73.916466           K
3881985       <18        M     WHITE  40.625264 -73.998697           K
3881986     18-24        M     BLACK  40.801304 -73.936106           M
3881987     25-44        M     BLACK  40.675505 -73.899692           K
3881988     45-64        M     BLACK  40.804428 -73.955370           M

         arrest_precinct  jurisdiction_code  :@computed_region_f5dn_yrer  \
0                     25                0.0                          7.0
1                     14                0.0                         12.0
2                     67                0.0                         61.0
3                     77                0.0                         16.0
4                     77                2.0                         16.0
...                  ...                ...                          ...
3881984               73                0.0                         69.0
3881985               62                0.0                         10.0
3881986               25                0.0                          7.0
3881987               75                0.0                         45.0
3881988               28                2.0                         18.0

         :@computed_region_yeji_bk3q  :@computed_region_92fq_4b7q  \
0                                4.0                         36.0
1                                4.0                         10.0
2                                2.0                         11.0
3                                2.0                         49.0
4                                2.0                         49.0
...                              ...                          ...
3881984                          2.0                         17.0
3881985                          2.0                          7.0
3881986                          4.0                         35.0
3881987                          2.0                         37.0
3881988                          4.0                         36.0

         :@computed_region_sbqj_enih
0                               16.0
1                                8.0
2                               40.0
3                               49.0
4                               49.0
...                              ...
3881984                         52.0
3881985                         41.0
3881986                         16.0
3881987                         47.0
3881988                         18.0

[3881989 rows x 19 columns]

In [78]:
#Rename columns for consistency
crime = crime.rename(columns={':@computed_region_f5dn_yrer': 'community_districts', 
                              ':@computed_region_yeji_bk3q': 'borough_boundaries',  
                              ':@computed_region_92fq_4b7q': 'city_council_districts',
                              ':@computed_region_sbqj_enih': 'police_precincts',
                              })

In [79]:
airbnb['neighbourhood_group_cleansed']

0        Manhattan
1        Manhattan
2         Brooklyn
3        Manhattan
4        Manhattan
           ...
48859       Queens
48860    Manhattan
48861    Manhattan
48862    Manhattan
48863    Manhattan
Name: neighbourhood_group_cleansed, Length: 48864, dtype: object

In [80]:
airbnb.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
name                                             object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 106, dtype: object

In [81]:
#Check unique values in order to decide wich columns to keep in crime dataset
print(airbnb['neighbourhood_group_cleansed'].unique())
print(airbnb['neighbourhood_cleansed'].unique())

['Manhattan' 'Brooklyn' 'Queens' 'Staten Island' 'Bronx']
['Midtown' 'Harlem' 'Clinton Hill' 'East Harlem' 'Murray Hill'
 'Bedford-Stuyvesant' "Hell's Kitchen" 'Upper West Side' 'East Village'
 'Chinatown' 'South Slope' 'West Village' 'Williamsburg' 'Fort Greene'
 'Chelsea' 'Crown Heights' 'Park Slope' 'Windsor Terrace' 'Inwood'
 'Greenpoint' 'Bushwick' 'Flatbush' 'Lower East Side'
 'Prospect-Lefferts Gardens' 'Long Island City' 'Kips Bay' 'SoHo'
 'Upper East Side' 'Red Hook' 'Prospect Heights' 'Washington Heights'
 'Woodside' 'Brooklyn Heights' 'Carroll Gardens' 'Gowanus' 'Flatlands'
 'Cobble Hill' 'Flushing' 'Boerum Hill' 'Sunnyside' 'DUMBO' 'St. George'
 'Highbridge' 'Financial District' 'Ridgewood' 'Morningside Heights'
 'Jamaica' 'Middle Village' 'NoHo' 'Ditmars Steinway' 'Flatiron District'
 'Roosevelt Island' 'Greenwich Village' 'Little Italy' 'Tompkinsville'
 'Astoria' 'Kensington' 'Clason Point' 'Eastchester' 'Kingsbridge'
 'Two Bridges' 'Queens Village' 'Rockaway Beach' 'Forest Hills'
 'East Flatbush' 'Nolita' 'Woodlawn' 'University Heights' 'Gravesend'
 'Gramercy' 'Allerton' 'East New York' 'Theater District'
 'Concourse Village' 'Sheepshead Bay' 'Emerson Hill' 'Fort Hamilton'
 'Bensonhurst' 'Tribeca' 'Shore Acres' 'Sunset Park' 'Concourse'
 'Vinegar Hill' 'Elmhurst' 'Brighton Beach' 'Jackson Heights'
 'Cypress Hills' 'St. Albans' 'Arrochar' 'Rego Park' 'Wakefield' 'Clifton'
 'Bay Ridge' 'Graniteville' 'Spuyten Duyvil' 'Stapleton' 'Briarwood'
 'Ozone Park' 'Columbia St' 'Mott Haven' 'Longwood' 'Canarsie'
 'Battery Park City' 'Civic Center' 'East Elmhurst' 'New Springville'
 'Morris Heights' 'Arverne' 'Cambria Heights' 'Tottenville' 'Maspeth'
 'Mariners Harbor' 'Concord' 'Borough Park' 'Bayside' 'Downtown Brooklyn'
 'Port Morris' 'Fieldston' 'Kew Gardens' 'Midwood' 'College Point'
 'Mount Eden' 'City Island' 'Glendale' 'Richmond Hill' 'Williamsbridge'
 'Soundview' 'Woodhaven' 'Woodrow' 'Co-op City' 'Stuyvesant Town'
 'Parkchester' 'North Riverdale' 'Dyker Heights' 'Bronxdale' 'Sea Gate'
 'Riverdale' 'Kew Gardens Hills' 'Bay Terrace' 'Norwood'
 'Claremont Village' 'Whitestone' 'Fordham' 'Bayswater' 'Brownsville'
 'Eltingville' 'Mount Hope' 'Fresh Meadows' 'Navy Yard' 'Lighthouse Hill'
 'Unionport' 'Howard Beach' 'Belle Harbor' 'Jamaica Estates' 'Van Nest'
 'Bellerose' 'Morris Park' 'West Brighton' 'Far Rockaway'
 'South Ozone Park' 'Tremont' 'Corona' 'Springfield Gardens' 'Great Kills'
 'Manhattan Beach' 'Marble Hill' 'Dongan Hills' 'Castleton Corners'
 'East Morrisania' 'Hunts Point' 'Neponsit' 'Pelham Bay' 'Randall Manor'
 'Throgs Neck' 'Todt Hill' 'West Farms' 'Silver Lake' 'Morrisania'
 'Laurelton' 'Grymes Hill' 'Holliswood' 'Pelham Gardens' 'Belmont'
 'Rosedale' 'Edgemere' 'New Brighton' 'Midland Beach' 'Baychester'
 'Melrose' 'Bergen Beach' 'Richmondtown' 'Howland Hook' 'Schuylerville'
 'Coney Island' 'New Dorp Beach' "Prince's Bay" 'South Beach' 'Bath Beach'
 'Jamaica Hills' 'Oakwood' 'Castle Hill' 'Hollis' 'Douglaston' 'Huguenot'
 'Olinville' 'Edenwald' 'Grant City' 'Port Richmond' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Westchester Square' 'Little Neck'
 'Fort Wadsworth' 'Rosebank' 'Mill Basin' 'Arden Heights' "Bull's Head"
 'New Dorp' 'Rossville' 'Breezy Point' 'Willowbrook' 'Country Club']

In [82]:
#Check Columns 
print(airbnb.columns)
print(crime.columns)

# Drop columns that are not needed and exist in the dataframe
airbnb = airbnb[['id','last_review','reviews_per_month','calculated_host_listings_count','availability_365', 
                'neighbourhood_group_cleansed','neighbourhood_cleansed','latitude','longitude','price','minimum_nights',
                'number_of_reviews','room_type', 'bedrooms','bathrooms','beds','review_scores_rating','review_scores_accuracy',
                'review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location',
                'review_scores_value']]

crime = crime[['arrest_date', 'ofns_desc', 'law_cat_cd', 'latitude', 'longitude','borough_boundaries']]

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)
Index(['Unnamed: 0', 'arrest_key', 'arrest_date', 'pd_desc', 'ofns_desc',
       'law_code', 'law_cat_cd', 'age_group', 'perp_sex', 'perp_race',
       'latitude', 'longitude', 'arrest_boro', 'arrest_precinct',
       'jurisdiction_code', 'community_districts', 'borough_boundaries',
       'city_council_districts', 'police_precincts'],
      dtype='object')

In [83]:
#Check null values
print(airbnb.isna().sum())
print(crime.isna().sum())

#Drop rows with null values
airbnb = airbnb.dropna()
crime = crime.dropna()

id                                    0
last_review                       10131
reviews_per_month                 10131
calculated_host_listings_count        0
availability_365                      0
neighbourhood_group_cleansed          0
neighbourhood_cleansed                0
latitude                              0
longitude                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
room_type                             0
bedrooms                             27
bathrooms                            56
beds                                 42
review_scores_rating              11104
review_scores_accuracy            11142
review_scores_cleanliness         11126
review_scores_checkin             11158
review_scores_communication       11136
review_scores_location            11163
review_scores_value               11161
dtype: int64
arrest_date               0
ofns_desc                 0
law_cat_cd            13360
latitude                  0
longitude                 0
borough_boundaries     5980
dtype: int64

In [84]:
airbnb.shape

(37603, 23)

In [85]:
#Check data types
print(airbnb.dtypes)
print(crime.dtypes)

id                                  int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
neighbourhood_group_cleansed       object
neighbourhood_cleansed             object
latitude                          float64
longitude                         float64
price                              object
minimum_nights                      int64
number_of_reviews                   int64
room_type                          object
bedrooms                          float64
bathrooms                         float64
beds                              float64
review_scores_rating              float64
review_scores_accuracy            float64
review_scores_cleanliness         float64
review_scores_checkin             float64
review_scores_communication       float64
review_scores_location            float64
review_scores_value               float64
dtype: object
arrest_date            object
ofns_desc              object
law_cat_cd             object
latitude              float64
longitude             float64
borough_boundaries    float64
dtype: object

In [86]:
# Rename column to match the neighbourhood group in airnb dataset
crime = crime.rename(columns={'borough_boundaries': 'neighbourhood_group_cleansed'})

# Map the neighbourhood_group to the crime dataset
crime['neighbourhood_group_cleansed'] = crime['neighbourhood_group_cleansed'].map({
    1.0: 'Manhattan',
    2.0: 'Bronx',
    3.0: 'Brooklyn',
    4.0: 'Queens',
    5.0: 'Staten Island'
})

In [87]:
#Coverting the 'arrest_date' and 'last review' to datetime format
crime['arrest_date'] = pd.to_datetime(crime['arrest_date'], format='%Y-%m-%d')
airbnb['last_review'] = pd.to_datetime(airbnb['last_review'], format='%Y-%m-%d')

In [88]:
#Find a threshold for arrest_date 
print(airbnb['last_review'].describe())
print(crime['arrest_date'].describe())

count                            37603
mean     2018-11-04 16:03:32.153285632
min                2011-03-28 00:00:00
25%                2018-08-16 00:00:00
50%                2019-06-11 00:00:00
75%                2019-07-21 00:00:00
max                2019-08-15 00:00:00
Name: last_review, dtype: object
count                          3862654
mean     2012-05-12 13:21:28.870710016
min                2006-01-01 00:00:00
25%                2009-02-20 00:00:00
50%                2012-02-22 00:00:00
75%                2015-06-06 00:00:00
max                2019-12-31 00:00:00
Name: arrest_date, dtype: object

In [89]:
# Filter the crime dataset to only include arrests after a specific date
crime = crime[
    (crime['arrest_date'] >= pd.Timestamp('2011-03-28')) &
(crime['arrest_date'] <= pd.Timestamp('2019-08-15'))
]

In [90]:
#chech duplicates
print(airbnb.duplicated().sum())
print(crime.duplicated().sum())

0
317326

In [91]:
#Remove duplicates
crime = crime.drop_duplicates()

In [92]:
# Aggregate crime data by neighbourhood_group
crime_grouped = crime.groupby('neighbourhood_group_cleansed').size().reset_index(name='crime_count')

# Merge the aggregated crime data with airnb
airbnb_crime = pd.merge(airbnb, crime_grouped, on='neighbourhood_group_cleansed', how='inner')

In [93]:
# Attractions with coordinates
nyc_attractions = {
    "Statue of Liberty": (40.689247, -74.044502),
    "Times Square": (40.758896, -73.985130),
    "Central Park": (40.785091, -73.968285),
    "Empire State Building": (40.748817, -73.985428),
    "Brooklyn Bridge": (40.706086, -73.996864),
    "Rockefeller Center": (40.758740, -73.978674),
    "One World Trade Center": (40.712742, -74.013382),
    "Broadway": (40.759011, -73.984472),
    "Grand Central Terminal": (40.752726, -73.977229),
    "The Metropolitan Museum of Art": (40.779437, -73.963244),
    "American Museum of Natural History": (40.781324, -73.973988),
    "9/11 Memorial & Museum": (40.711503, -74.013379),
    "Fifth Avenue": (40.775391, -73.965633),
    "Chrysler Building": (40.751652, -73.975311),
    "The High Line": (40.747992, -74.004764)
}

# Haversine distance function
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return R * c

# Loop through attractions and add new distance columns
for name, (lat, lon) in nyc_attractions.items():
    col_name = "distance_to_" + name.lower().replace(" ", "_").replace("&", "and") 
    airbnb_crime[col_name] = airbnb_crime.apply(lambda row: haversine(row["latitude"], row["longitude"], lat, lon), axis=1)

print(airbnb_crime.head())

     id last_review  reviews_per_month  calculated_host_listings_count  \
0  2595  2019-07-14               0.39                               2
1  3831  2019-07-26               4.64                               1
2  5099  2019-07-21               0.60                               1
3  5178  2019-07-13               3.48                               1
4  5203  2017-07-21               0.98                               1

   availability_365 neighbourhood_group_cleansed neighbourhood_cleansed  \
0               288                    Manhattan                Midtown
1               212                     Brooklyn           Clinton Hill
2               127                    Manhattan            Murray Hill
3               239                    Manhattan         Hell's Kitchen
4                 0                    Manhattan        Upper West Side

   latitude  longitude    price  ...  distance_to_rockefeller_center  \
0  40.75362  -73.98377  $225.00  ...                        0.712997
1  40.68514  -73.95976   $89.00  ...                        8.337723
2  40.74767  -73.97500  $200.00  ...                        1.269235
3  40.76489  -73.98493   $79.00  ...                        0.863289
4  40.80178  -73.96723   $79.00  ...                        4.881868

   distance_to_one_world_trade_center distance_to_broadway  \
0                            5.185197             0.602361
1                            5.463919             8.473967
2                            5.054090             1.492264
3                            6.274543             0.654852
4                           10.636374             4.972348

   distance_to_grand_central_terminal  \
0                            0.559866
1                            7.658067
2                            0.592728
3                            1.500058
4                            5.519153

   distance_to_the_metropolitan_museum_of_art  \
0                                    3.350997
1                                   10.489457
2                                    3.668465
3                                    2.439538
4                                    2.506988

   distance_to_american_museum_of_natural_history  \
0                                        3.188791
1                                       10.762152
2                                        3.743125
3                                        2.046533
4                                        2.344673

   distance_to_9/11_memorial_and_museum  distance_to_fifth_avenue  \
0                              5.306275                  2.862444
1                              5.387559                 10.047648
2                              5.160574                  3.181790
3                              6.401993                  2.001042
4                             10.764653                  2.937401

   distance_to_chrysler_building  distance_to_the_high_line
0                       0.745382                   1.875920
1                       7.511024                   7.951725
2                       0.443553                   2.507579
3                       1.680229                   2.514249
4                       5.615359                   6.764693

[5 rows x 39 columns]

In [94]:
airbnb_crime

,id,last_review,reviews_per_month,calculated_host_listings_count,availability_365,neighbourhood_group_cleansed,neighbourhood_cleansed,latitude,longitude,price,...,distance_to_rockefeller_center,distance_to_one_world_trade_center,distance_to_broadway,distance_to_grand_central_terminal,distance_to_the_metropolitan_museum_of_art,distance_to_american_museum_of_natural_history,distance_to_9/11_memorial_and_museum,distance_to_fifth_avenue,distance_to_chrysler_building,distance_to_the_high_line
0,2595,2019-07-14,0.39,2,288,Manhattan,Midtown,40.75362,-73.98377,$225.00,...,0.712997,5.185197,0.602361,0.559866,3.350997,3.188791,5.306275,2.862444,0.745382,1.875920
1,3831,2019-07-26,4.64,1,212,Brooklyn,Clinton Hill,40.68514,-73.95976,$89.00,...,8.337723,5.463919,8.473967,7.658067,10.489457,10.762152,5.387559,10.047648,7.511024,7.951725
2,5099,2019-07-21,0.60,1,127,Manhattan,Murray Hill,40.74767,-73.97500,$200.00,...,1.269235,5.054090,1.492264,0.592728,3.668465,3.743125,5.160574,3.181790,0.443553,2.507579
3,5178,2019-07-13,3.48,1,239,Manhattan,Hell's Kitchen,40.76489,-73.98493,$79.00,...,0.863289,6.274543,0.654852,1.500058,2.439538,2.046533,6.401993,2.001042,1.680229,2.514249
4,5203,2017-07-21,0.98,1,0,Manhattan,Upper West Side,40.80178,-73.96723,$79.00,...,4.881868,10.636374,4.972348,5.519153,2.506988,2.344673,10.764653,2.937401,5.615359,6.764693
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37598,37367709,2019-08-04,1.00,2,69,Brooklyn,Sheepshead Bay,40.59593,-73.95854,$57.00,...,18.183091,13.788219,18.265163,17.506014,20.408902,20.655979,13.658443,19.964113,17.373164,17.352098
37599,37400191,2019-08-04,1.00,2,86,Brooklyn,Sheepshead Bay,40.59592,-73.95760,$60.00,...,18.191771,13.816074,18.275926,17.514436,20.411707,20.662237,13.686549,19.967756,17.380905,17.371162
37600,37400410,2019-08-05,1.00,1,347,Brooklyn,Greenpoint,40.73467,-73.95131,$229.00,...,3.532326,5.771222,3.889721,2.966297,5.078338,5.528165,5.830583,4.685936,2.766616,4.740789
37601,37416939,2019-08-15,2.00,1,1,Brooklyn,Bushwick,40.70497,-73.92173,$60.00,...,7.666148,7.773487,8.003611,7.075935,8.988678,9.563753,7.759199,8.660100,6.879651,8.476059
37602,37447887,2019-08-06,1.00,1,177,Manhattan,Lower East Side,40.72066,-73.98385,$312.00,...,4.256699,2.640079,4.264759,3.608951,6.762278,6.796491,2.688950,6.276310,3.520452,3.513091

In [95]:
#convert string to float
airbnb_crime['price'] = airbnb_crime['price'].replace('[\$,]', '', regex=True).astype(float)

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
C:\Users\anais\AppData\Local\Temp\ipykernel_14520\652640240.py:2: SyntaxWarning: invalid escape sequence '\$'
  airbnb_crime['price'] = airbnb_crime['price'].replace('[\$,]', '', regex=True).astype(float)

In [96]:
# Save the cleaned datasets to CSV files
airbnb_crime.to_csv('cleaned_airbnb_crime.csv', index=False)

In [97]:
#check columns
print(airbnb_crime.columns)

Index(['id', 'last_review', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365',
       'neighbourhood_group_cleansed', 'neighbourhood_cleansed', 'latitude',
       'longitude', 'price', 'minimum_nights', 'number_of_reviews',
       'room_type', 'bedrooms', 'bathrooms', 'beds', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'crime_count',
       'distance_to_statue_of_liberty', 'distance_to_times_square',
       'distance_to_central_park', 'distance_to_empire_state_building',
       'distance_to_brooklyn_bridge', 'distance_to_rockefeller_center',
       'distance_to_one_world_trade_center', 'distance_to_broadway',
       'distance_to_grand_central_terminal',
       'distance_to_the_metropolitan_museum_of_art',
       'distance_to_american_museum_of_natural_history',
       'distance_to_9/11_memorial_and_museum', 'distance_to_fifth_avenue',
       'distance_to_chrysler_building', 'distance_to_the_high_line'],
      dtype='object')