In [118]:
import os
import csv
import pandas as pd
import numpy as np
#load datasets

airbnb = pd.read_csv('new_york_listings_2024.csv')
crime = pd.read_csv('NYPD_Arrest_Data_2023.csv')

In [119]:
#Visualize data
print(airbnb)
print(crime)

                       id                                               name  \
0                 1312228         Rental unit in Brooklyn · ★5.0 · 1 bedroom
1                45277537  Rental unit in New York · ★4.67 · 2 bedrooms ·...
2      971353993633883038  Rental unit in New York · ★4.17 · 1 bedroom · ...
3                 3857863  Rental unit in New York · ★4.64 · 1 bedroom · ...
4                40896611  Condo in New York · ★4.91 · Studio · 1 bed · 1...
...                   ...                                                ...
20753            24736896  Rental unit in New York · ★4.75 · 1 bedroom · ...
20754             2835711  Rental unit in New York · ★4.46 · 1 bedroom · ...
20755            51825274  Rental unit in New York · ★4.93 · 1 bedroom · ...
20756  782661008019550832  Rental unit in New York · ★5.0 · 1 bedroom · 1...
20757  566029911248687183  Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...

         host_id           host_name neighbourhood_group       neighbourhood  \
0        7130382              Walter            Brooklyn        Clinton Hill
1       51501835            Jeniffer           Manhattan      Hell's Kitchen
2      528871354              Joshua           Manhattan             Chelsea
3       19902271  John And Catherine           Manhattan  Washington Heights
4       61391963      Stay With Vibe           Manhattan         Murray Hill
...          ...                 ...                 ...                 ...
20753  186680487             Henry D           Manhattan     Lower East Side
20754    3237504               Aspen           Manhattan   Greenwich Village
20755  304317395                Jeff           Manhattan      Hell's Kitchen
20756  163083101             Marissa           Manhattan           Chinatown
20757   93827372             Glenroy              Queens            Rosedale

        latitude  longitude        room_type  price  ...  last_review  \
0      40.683710 -73.964610     Private room   55.0  ...   2015-12-20
1      40.766610 -73.988100  Entire home/apt  144.0  ...   2023-05-01
2      40.750764 -73.994605  Entire home/apt  187.0  ...   2023-12-18
3      40.835600 -73.942500     Private room  120.0  ...   2023-09-17
4      40.751120 -73.978600  Entire home/apt   85.0  ...   2023-12-03
...          ...        ...              ...    ...  ...          ...
20753  40.711380 -73.991560     Private room   45.0  ...   2023-09-29
20754  40.730580 -74.000700  Entire home/apt  105.0  ...   2023-07-01
20755  40.757350 -73.993430  Entire home/apt  299.0  ...   2023-12-08
20756  40.713750 -73.991470  Entire home/apt  115.0  ...   2023-09-17
20757  40.658874 -73.728651     Private room  102.0  ...   2023-12-10

       reviews_per_month calculated_host_listings_count  availability_365  \
0                   0.03                              1                 0
1                   0.24                            139               364
2                   1.67                              1               343
3                   1.38                              2               363
4                   0.24                            133               335
...                  ...                            ...               ...
20753               1.81                              1               157
20754               0.48                              1                 0
20755               2.09                              1                 0
20756               0.91                              1               363
20757               4.50                              1                 0

       number_of_reviews_ltm             license  rating bedrooms beds  \
0                          0          No License    5.0         1    1
1                          2          No License   4.67         2    1
2                          6              Exempt   4.17         1    2
3                         12          No License   4.64         1    1
4                          3          No License   4.91    Studio    1
...                      ...                 ...     ...      ...  ...
20753                     12          No License   4.75         1    1
20754                      1          No License   4.46         1    2
20755                     27          No License   4.93         1    1
20756                      7          No License    5.0         1    1
20757                     62  OSE-STRREG-0000513   4.89         1    1

               baths
0      Not specified
1                  1
2                  1
3                  1
4                  1
...              ...
20753              1
20754              1
20755              1
20756              1
20757              1

[20758 rows x 22 columns]
        ARREST_KEY ARREST_DATE  PD_CD                         PD_DESC  KY_CD  \
0        261209118  01/01/2023    109        ASSAULT 2,1,UNCLASSIFIED  106.0
1        262984267  02/03/2023    515     CONTROLLED SUBSTANCE,SALE 3  117.0
2        263664549  02/15/2023    105               STRANGULATION 1ST  106.0
3        261345231  01/04/2023    105               STRANGULATION 1ST  106.0
4        263536618  02/13/2023    109        ASSAULT 2,1,UNCLASSIFIED  106.0
...            ...         ...    ...                             ...    ...
170090   270955727  07/07/2023    397  ROBBERY,OPEN AREA UNCLASSIFIED  105.0
170091   273117887  08/18/2023    681      CHILD, ENDANGERING WELFARE  233.0
170092   274301006  09/13/2023    969  TRAFFIC,UNCLASSIFIED INFRACTIO  881.0
170093   269912233  06/15/2023    490    STOLEN PROPERTY 3,POSSESSION  232.0
170094   272045762  07/28/2023    729  FORGERY,ETC.,UNCLASSIFIED-FELO  113.0

                            OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  \
0                      FELONY ASSAULT  PL 1200501          F           K
1                     DANGEROUS DRUGS  PL 2203901          F           K
2                      FELONY ASSAULT  PL 1211200          F           K
3                      FELONY ASSAULT  PL 1211200          F           M
4                      FELONY ASSAULT  PL 12005WX          F           K
...                               ...         ...        ...         ...
170090                        ROBBERY  PL 1601002          F           B
170091                     SEX CRIMES  PL 2601001          M           B
170092       OTHER TRAFFIC INFRACTION  VTL051101A          M           S
170093  POSSESSION OF STOLEN PROPERTY  PL 1654000          M           K
170094                        FORGERY  PL 1702500          F           K

        ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX       PERP_RACE  \
0                    77                  0     45-64        F           BLACK
1                    73                  0     25-44        M           BLACK
2                    62                  0     25-44        M           WHITE
3                    32                  0     25-44        M           BLACK
4                    71                  0     25-44        M           BLACK
...                 ...                ...       ...      ...             ...
170090               52                  0     25-44        M           BLACK
170091               47                  0     25-44        F           BLACK
170092              122                  0     25-44        M  WHITE HISPANIC
170093               62                  0     25-44        M           BLACK
170094               84                  0     18-24        M           BLACK

        X_COORD_CD  Y_COORD_CD   Latitude  Longitude
0           999335      186085  40.677426 -73.945615
1          1009318      178259  40.655923 -73.909650
2           982272      158771  40.602468 -74.007120
3           999899      238684  40.821797 -73.943457
4          1001437      183080  40.669175 -73.938042
...            ...         ...        ...        ...
170090     1017273      255924  40.869067 -73.880600
170091     1026480      262584  40.887314 -73.847272
170092      951857      161569  40.610087 -74.116666
170093      983469      157947  40.600204 -74.002812
170094      988491      195163  40.702353 -73.984704

[170095 rows x 18 columns]

In [120]:
#Check null values
print(airbnb.isna().sum())
print(crime.isna().sum())

#Drop rows with null values
airbnb = airbnb.dropna()
crime = crime.dropna()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
rating                            0
bedrooms                          0
beds                              0
baths                             0
dtype: int64
ARREST_KEY              0
ARREST_DATE             0
PD_CD                   0
PD_DESC                 0
KY_CD                  13
OFNS_DESC               0
LAW_CODE                0
LAW_CAT_CD           1257
ARREST_BORO             0
ARREST_PRECINCT         0
JURISDICTION_CODE       0
AGE_GROUP               0
PERP_SEX                0
PERP_RACE               0
X_COORD_CD              0
Y_COORD_CD              0
Latitude                0
Longitude               0
dtype: int64

In [121]:
#Check unique values in order to decide wich columns to keep in crime dataset
print(airbnb['neighbourhood_group'].unique())
print(airbnb['neighbourhood'].unique())

['Brooklyn' 'Manhattan' 'Queens' 'Bronx' 'Staten Island']
['Clinton Hill' "Hell's Kitchen" 'Chelsea' 'Washington Heights'
 'Murray Hill' 'Williamsburg' 'Sunset Park' 'Astoria' 'Financial District'
 'Sunnyside' 'Midtown' 'East Elmhurst' 'Upper West Side' 'West Village'
 'Kensington' 'Bushwick' 'Red Hook' 'Tribeca' 'Woodside'
 'Roosevelt Island' 'Concourse Village' 'Harlem' 'Flatbush'
 'University Heights' 'Flushing' 'Greenpoint' 'Ridgewood' 'Cypress Hills'
 "Prince's Bay" 'Port Richmond' 'East Village' 'Clason Point'
 'Bedford-Stuyvesant' 'Gravesend' 'Long Island City' 'Gramercy'
 'East Flatbush' 'East Harlem' 'St. George' 'Boerum Hill'
 'South Ozone Park' 'Park Slope' 'Crown Heights' 'Wakefield'
 'Forest Hills' 'Springfield Gardens' 'North Riverdale' 'Belmont' 'Corona'
 'Tremont' 'Elmhurst' 'Queens Village' 'Prospect-Lefferts Gardens'
 'Fort Greene' 'Allerton' 'Upper East Side' 'Richmond Hill' 'Kips Bay'
 'Morningside Heights' 'Flatlands' 'St. Albans' 'Bay Ridge' 'SoHo'
 'Lower East Side' 'West Brighton' 'Parkchester' 'Brownsville'
 'Ozone Park' 'Jackson Heights' 'Kew Gardens' 'Prospect Heights' 'Jamaica'
 'Arrochar' 'Kew Gardens Hills' 'Laurelton' 'Morris Park' 'Rosedale'
 'Arverne' 'Woodhaven' 'Norwood' 'Rosebank' 'Tompkinsville'
 'East New York' 'Far Rockaway' 'Edenwald' 'Baychester' 'Canarsie'
 'Williamsbridge' 'Kingsbridge' 'Rego Park' 'Sheepshead Bay'
 'Ditmars Steinway' 'Melrose' 'DUMBO' 'Theater District' 'Civic Center'
 'Chinatown' 'Flatiron District' 'Nolita' 'Bath Beach' 'East Morrisania'
 'Little Italy' 'Fresh Meadows' 'Midwood' 'Glendale' 'West Farms'
 'Carroll Gardens' 'Mount Hope' 'Gowanus' 'Windsor Terrace'
 'Downtown Brooklyn' 'Maspeth' 'South Slope' "Bull's Head" 'Navy Yard'
 'Stuyvesant Town' 'Borough Park' 'Dyker Heights' 'Greenwich Village'
 'College Point' 'Rockaway Beach' 'Mott Haven' 'Oakwood' 'Morris Heights'
 'Inwood' 'Cobble Hill' 'Jamaica Estates' 'Brighton Beach'
 'Brooklyn Heights' 'Vinegar Hill' 'Hollis' 'Jamaica Hills' 'Coney Island'
 'Arden Heights' 'New Springville' 'Bensonhurst' 'Howard Beach'
 'Throgs Neck' 'Cambria Heights' 'Battery Park City' 'Bayside' 'Briarwood'
 'Longwood' 'Shore Acres' 'Fordham' 'Whitestone' 'Unionport' 'Castle Hill'
 'Bergen Beach' 'Bayswater' 'Port Morris' 'Middle Village' 'NoHo'
 'Bellerose' 'Mount Eden' 'Emerson Hill' 'Pelham Bay' 'Randall Manor'
 'Mill Basin' 'Fort Hamilton' 'Eltingville' 'Woodrow' 'Clifton'
 'New Dorp Beach' 'Grant City' 'Edgemere' 'Lighthouse Hill' 'South Beach'
 'Rossville' 'Belle Harbor' 'New Brighton' 'Van Nest' 'Hunts Point'
 'Westchester Square' 'Spuyten Duyvil' 'Mariners Harbor' 'Midland Beach'
 'Concourse' 'Tottenville' 'Schuylerville' 'Marble Hill' 'Co-op City'
 'Stapleton' 'Morrisania' 'Claremont Village' 'Two Bridges' 'Concord'
 'Holliswood' 'Dongan Hills' 'City Island' 'Eastchester' 'Columbia St'
 'Bronxdale' 'Douglaston' 'Pelham Gardens' 'Olinville' 'Fieldston'
 'Highbridge' 'Richmondtown' 'Woodlawn' 'Bay Terrace' 'Huguenot'
 'Manhattan Beach' 'Silver Lake' 'Castleton Corners' 'Howland Hook'
 'Gerritsen Beach' 'Graniteville' 'Riverdale' 'Great Kills' 'Sea Gate'
 'Grymes Hill' 'Soundview' 'Breezy Point' 'Westerleigh'
 'Bay Terrace, Staten Island' 'Little Neck' 'Todt Hill' 'Neponsit'
 'Willowbrook' 'Chelsea, Staten Island']

In [122]:
# Standardize column names
airbnb.columns = airbnb.columns.str.lower()
crime.columns = crime.columns.str.lower()

# Drop unneeded columns from airbnb
airbnb = airbnb.drop(columns=['name','host_id','host_name','neighbourhood','license'])

# Select subset of columns from crime
crime = crime[['arrest_date', 'ofns_desc', 'law_cat_cd', 'latitude', 'longitude', 'arrest_boro']]

In [123]:
#Check data types
print(airbnb.dtypes)
print(crime.dtypes)

id                                  int64
neighbourhood_group                object
latitude                          float64
longitude                         float64
room_type                          object
price                             float64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
number_of_reviews_ltm               int64
rating                             object
bedrooms                           object
beds                                int64
baths                              object
dtype: object
arrest_date     object
ofns_desc       object
law_cat_cd      object
latitude       float64
longitude      float64
arrest_boro     object
dtype: object

In [124]:
crime

,arrest_date,ofns_desc,law_cat_cd,latitude,longitude,arrest_boro
0,01/01/2023,FELONY ASSAULT,F,40.677426,-73.945615,K
1,02/03/2023,DANGEROUS DRUGS,F,40.655923,-73.909650,K
2,02/15/2023,FELONY ASSAULT,F,40.602468,-74.007120,K
3,01/04/2023,FELONY ASSAULT,F,40.821797,-73.943457,M
4,02/13/2023,FELONY ASSAULT,F,40.669175,-73.938042,K
...,...,...,...,...,...,...
170090,07/07/2023,ROBBERY,F,40.869067,-73.880600,B
170091,08/18/2023,SEX CRIMES,M,40.887314,-73.847272,B
170092,09/13/2023,OTHER TRAFFIC INFRACTION,M,40.610087,-74.116666,S
170093,06/15/2023,POSSESSION OF STOLEN PROPERTY,M,40.600204,-74.002812,K
170094,07/28/2023,FORGERY,F,40.702353,-73.984704,K

In [125]:
# Rename column to match the neighbourhood group in airnb dataset
crime = crime.rename(columns={'arrest_boro': 'neighbourhood_group'})

# Map the neighbourhood_group to the crime dataset
crime['neighbourhood_group'] = crime['neighbourhood_group'].map({
  'B': 'Bronx',
    'K': 'Brooklyn',
    'M': 'Manhattan',
    'Q': 'Queens',
    'S': 'Staten Island'
})

In [126]:
#Coverting the 'arrest_date' and 'last review' to datetime format
crime['arrest_date'] = pd.to_datetime(crime['arrest_date'], errors='coerce')

airbnb['last_review'] = pd.to_datetime(airbnb['last_review'], errors='coerce')

In [127]:
#Find a threshold for arrest_date 
print(airbnb['last_review'].describe())
print(crime['arrest_date'].describe())

count                            20758
mean     2023-02-24 12:28:55.658541312
min                2011-12-10 00:00:00
25%                2023-04-08 00:00:00
50%                2023-09-20 00:00:00
75%                2023-11-25 00:00:00
max                2024-01-05 00:00:00
Name: last_review, dtype: object
count                           168825
mean     2023-05-17 21:45:40.094180352
min                2023-01-01 00:00:00
25%                2023-03-11 00:00:00
50%                2023-05-19 00:00:00
75%                2023-07-25 00:00:00
max                2023-09-30 00:00:00
Name: arrest_date, dtype: object

In [128]:
# Filter the crime dataset to only include arrests after a specific date
crime = crime[crime['arrest_date'] >= pd.Timestamp('2023-01-01')]
# Filter the airbnb dataset to only include listings with last review  a specific date
airbnb = airbnb[
    (airbnb['last_review'] >= pd.Timestamp('2023-01-01')) &
    (airbnb['last_review'] <= pd.Timestamp('2023-09-30'))
]

In [129]:
#chech duplicates
print(airbnb.duplicated().sum())
print(crime.duplicated().sum())

0
28773

In [130]:
#Remove duplicates
crime = crime.drop_duplicates()

In [131]:
# Aggregate crime data by neighbourhood_group
crime_grouped = crime.groupby('neighbourhood_group').size().reset_index(name='crime_count')

# Merge the aggregated crime data with airnb
airbnb_crime = pd.merge(airbnb, crime_grouped, on='neighbourhood_group', how='inner')

In [132]:
airbnb_crime

,id,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,rating,bedrooms,beds,baths,crime_count
0,45277537,Manhattan,40.766610,-73.988100,Entire home/apt,144.0,30,9,2023-05-01,0.24,139,364,2,4.67,2,1,1,31809
1,3857863,Manhattan,40.835600,-73.942500,Private room,120.0,30,156,2023-09-17,1.38,2,363,12,4.64,1,1,1,31809
2,49584983,Manhattan,40.759950,-73.992960,Entire home/apt,115.0,30,5,2023-07-29,0.16,139,276,2,5.0,1,1,1,31809
3,45847112,Manhattan,40.765190,-73.990130,Entire home/apt,130.0,30,10,2023-05-30,0.26,139,295,2,4.50,2,2,1,31809
4,17367484,Queens,40.760680,-73.909260,Private room,120.0,30,1,2023-08-21,0.22,1,365,1,No rating,1,2,1,29765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6678,791754056397616680,Manhattan,40.716593,-73.987383,Private room,79.0,30,6,2023-07-31,0.49,1,180,4,5.0,1,1,Not specified,31809
6679,897176430920178886,Manhattan,40.764520,-73.977920,Entire home/apt,140.0,35,1,2023-07-31,0.19,1,267,1,No rating,1,1,1,31809
6680,24736896,Manhattan,40.711380,-73.991560,Private room,45.0,30,124,2023-09-29,1.81,1,157,12,4.75,1,1,1,31809
6681,2835711,Manhattan,40.730580,-74.000700,Entire home/apt,105.0,30,56,2023-07-01,0.48,1,0,1,4.46,1,2,1,31809
6682,782661008019550832,Manhattan,40.713750,-73.991470,Entire home/apt,115.0,30,7,2023-09-17,0.91,1,363,7,5.0,1,1,1,31809

In [133]:
# Attractions with coordinates
nyc_attractions = {
    "Statue of Liberty": (40.689247, -74.044502),
    "Times Square": (40.758896, -73.985130),
    "Central Park": (40.785091, -73.968285),
    "Empire State Building": (40.748817, -73.985428),
    "Brooklyn Bridge": (40.706086, -73.996864),
    "Rockefeller Center": (40.758740, -73.978674),
    "One World Trade Center": (40.712742, -74.013382),
    "Broadway": (40.759011, -73.984472),
    "Grand Central Terminal": (40.752726, -73.977229),
    "The Metropolitan Museum of Art": (40.779437, -73.963244),
    "American Museum of Natural History": (40.781324, -73.973988),
    "9/11 Memorial & Museum": (40.711503, -74.013379),
    "Fifth Avenue": (40.775391, -73.965633),
    "Chrysler Building": (40.751652, -73.975311),
    "The High Line": (40.747992, -74.004764)
}

# Haversine distance function
def haversine(lat1, lon1, lat2, lon2):
    R = 6371  # Earth radius in km
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2)**2 + np.cos(lat1)*np.cos(lat2)*np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    return R * c

# Loop through attractions and add new distance columns
for name, (lat, lon) in nyc_attractions.items():
    col_name = "distance_to_" + name.lower().replace(" ", "_").replace("&", "and") 
    airbnb_crime[col_name] = airbnb_crime.apply(lambda row: haversine(row["latitude"], row["longitude"], lat, lon), axis=1)

print(airbnb_crime.head())

         id neighbourhood_group  latitude  longitude        room_type  price  \
0  45277537           Manhattan  40.76661  -73.98810  Entire home/apt  144.0
1   3857863           Manhattan  40.83560  -73.94250     Private room  120.0
2  49584983           Manhattan  40.75995  -73.99296  Entire home/apt  115.0
3  45847112           Manhattan  40.76519  -73.99013  Entire home/apt  130.0
4  17367484              Queens  40.76068  -73.90926     Private room  120.0

   minimum_nights  number_of_reviews last_review  reviews_per_month  ...  \
0              30                  9  2023-05-01               0.24  ...
1              30                156  2023-09-17               1.38  ...
2              30                  5  2023-07-29               0.16  ...
3              30                 10  2023-05-30               0.26  ...
4              30                  1  2023-08-21               0.22  ...

   distance_to_rockefeller_center  distance_to_one_world_trade_center  \
0                        1.181540                            6.357300
1                        9.072703                           14.908181
2                        1.210745                            5.524100
3                        1.202215                            6.152186
4                        5.850378                           10.265202

   distance_to_broadway distance_to_grand_central_terminal  \
0              0.898520                           1.794925
1              9.220101                           9.667802
2              0.722489                           1.549485
3              0.836151                           1.761111
4              6.337442                           5.792869

  distance_to_the_metropolitan_museum_of_art  \
0                                   2.532845
1                                   6.484499
2                                   3.310219
3                                   2.763255
4                                   5.001709

   distance_to_american_museum_of_natural_history  \
0                                        2.022133
1                                        6.591436
2                                        2.863758
3                                        2.250813
4                                        5.914433

  distance_to_9/11_memorial_and_museum  distance_to_fifth_avenue  \
0                             6.487195                  2.129058
1                            15.034451                  6.972310
2                             5.655107                  2.871260
3                             6.282865                  2.354215
4                            10.337268                  5.021340

   distance_to_chrysler_building  distance_to_the_high_line
0                       1.981589                   2.501174
1                       9.734669                  11.062235
2                       1.749650                   1.660304
3                       1.955503                   2.275155
4                       5.653291                   8.167262

[5 rows x 33 columns]

In [134]:
airbnb_crime

,id,neighbourhood_group,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,...,distance_to_rockefeller_center,distance_to_one_world_trade_center,distance_to_broadway,distance_to_grand_central_terminal,distance_to_the_metropolitan_museum_of_art,distance_to_american_museum_of_natural_history,distance_to_9/11_memorial_and_museum,distance_to_fifth_avenue,distance_to_chrysler_building,distance_to_the_high_line
0,45277537,Manhattan,40.766610,-73.988100,Entire home/apt,144.0,30,9,2023-05-01,0.24,...,1.181540,6.357300,0.898520,1.794925,2.532845,2.022133,6.487195,2.129058,1.981589,2.501174
1,3857863,Manhattan,40.835600,-73.942500,Private room,120.0,30,156,2023-09-17,1.38,...,9.072703,14.908181,9.220101,9.667802,6.484499,6.591436,15.034451,6.972310,9.734669,11.062235
2,49584983,Manhattan,40.759950,-73.992960,Entire home/apt,115.0,30,5,2023-07-29,0.16,...,1.210745,5.524100,0.722489,1.549485,3.310219,2.863758,5.655107,2.871260,1.749650,1.660304
3,45847112,Manhattan,40.765190,-73.990130,Entire home/apt,130.0,30,10,2023-05-30,0.26,...,1.202215,6.152186,0.836151,1.761111,2.763255,2.250813,6.282865,2.354215,1.955503,2.275155
4,17367484,Queens,40.760680,-73.909260,Private room,120.0,30,1,2023-08-21,0.22,...,5.850378,10.265202,6.337442,5.792869,5.001709,5.914433,10.337268,5.021340,5.653291,8.167262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6678,791754056397616680,Manhattan,40.716593,-73.987383,Private room,79.0,30,6,2023-07-31,0.49,...,4.743641,2.232735,4.723058,4.107898,7.277798,7.285684,2.262974,6.789942,4.028906,3.786163
6679,897176430920178886,Manhattan,40.764520,-73.977920,Entire home/apt,140.0,35,1,2023-07-31,0.19,...,0.645836,6.486510,0.824474,1.312724,2.068482,1.897629,6.608998,1.591173,1.447632,2.913759
6680,24736896,Manhattan,40.711380,-73.991560,Private room,45.0,30,124,2023-09-29,1.81,...,5.376949,1.845501,5.329889,4.753401,7.934654,7.917040,1.839092,7.445303,4.682675,4.220367
6681,2835711,Manhattan,40.730580,-74.000700,Entire home/apt,105.0,30,56,2023-07-01,0.48,...,3.639757,2.253106,3.444319,3.158174,6.282312,6.074520,2.375181,5.792487,3.172599,1.966169
6682,782661008019550832,Manhattan,40.713750,-73.991470,Entire home/apt,115.0,30,7,2023-09-17,0.91,...,5.117515,1.850227,5.067214,4.496977,7.681359,7.656847,1.863420,7.191472,4.428984,3.968895

In [135]:
#check columns
print(airbnb_crime.columns)

Index(['id', 'neighbourhood_group', 'latitude', 'longitude', 'room_type',
       'price', 'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'rating', 'bedrooms',
       'beds', 'baths', 'crime_count', 'distance_to_statue_of_liberty',
       'distance_to_times_square', 'distance_to_central_park',
       'distance_to_empire_state_building', 'distance_to_brooklyn_bridge',
       'distance_to_rockefeller_center', 'distance_to_one_world_trade_center',
       'distance_to_broadway', 'distance_to_grand_central_terminal',
       'distance_to_the_metropolitan_museum_of_art',
       'distance_to_american_museum_of_natural_history',
       'distance_to_9/11_memorial_and_museum', 'distance_to_fifth_avenue',
       'distance_to_chrysler_building', 'distance_to_the_high_line'],
      dtype='object')

In [136]:
airbnb_crime.shape

(6683, 33)

In [137]:
airbnb_crime.dtypes

id                                                         int64
neighbourhood_group                                       object
latitude                                                 float64
longitude                                                float64
room_type                                                 object
price                                                    float64
minimum_nights                                             int64
number_of_reviews                                          int64
last_review                                       datetime64[ns]
reviews_per_month                                        float64
calculated_host_listings_count                             int64
availability_365                                           int64
number_of_reviews_ltm                                      int64
rating                                                    object
bedrooms                                                  object
beds                                                       int64
baths                                                     object
crime_count                                                int64
distance_to_statue_of_liberty                            float64
distance_to_times_square                                 float64
distance_to_central_park                                 float64
distance_to_empire_state_building                        float64
distance_to_brooklyn_bridge                              float64
distance_to_rockefeller_center                           float64
distance_to_one_world_trade_center                       float64
distance_to_broadway                                     float64
distance_to_grand_central_terminal                       float64
distance_to_the_metropolitan_museum_of_art               float64
distance_to_american_museum_of_natural_history           float64
distance_to_9/11_memorial_and_museum                     float64
distance_to_fifth_avenue                                 float64
distance_to_chrysler_building                            float64
distance_to_the_high_line                                float64
dtype: object

In [138]:
print(airbnb_crime['rating'].unique())
print(airbnb_crime['baths'].unique())
print(airbnb_crime['bedrooms'].unique())

['4.67 ' '4.64 ' '5.0 ' '4.50 ' 'No rating' '4.73 ' '4.45 ' '4.58 '
 '4.42 ' '4.81 ' '3.84 ' '4.27 ' '4.21 ' '4.61 ' '4.40 ' '4.94 ' '4.76 '
 '4.69 ' '4.60 ' '4.33 ' '3.0 ' '4.78 ' '4.80 ' '4.87 ' '4.74 ' '4.71 '
 '4.83 ' '4.89 ' '4.72 ' '4.25 ' '4.0 ' '4.95 ' '4.88 ' '4.97 ' '4.18 '
 '4.86 ' '4.90 ' '4.82 ' '4.38 ' '4.85 ' '4.75 ' '4.43 ' '4.68 ' '4.29 '
 '4.20 ' '4.93 ' '4.98 ' '4.55 ' '4.92 ' '4.56 ' '4.30 ' '4.47 ' '4.63 '
 '4.96 ' '4.39 ' '4.36 ' '4.91 ' '4.70 ' '3.60 ' '4.35 ' '4.84 ' '3.88 '
 '3.92 ' '3.67 ' '4.66 ' '4.77 ' '4.79 ' '4.46 ' '3.86 ' '4.07 ' '4.23 '
 '4.31 ' '4.13 ' '3.75 ' '3.33 ' '4.59 ' '4.52 ' '4.16 ' '2.83 ' '3.80 '
 '4.41 ' '4.48 ' '3.71 ' '4.57 ' '3.36 ' '4.62 ' '4.22 ' '4.53 ' '4.17 '
 '3.89 ' '4.19 ' '4.65 ' '4.04 ' '4.54 ' '4.51 ' '4.26 ' '3.93 ' '4.99 '
 '3.57 ' '3.17 ' '3.50 ' '4.44 ' '4.06 ' '3.78 ' '4.49 ' '4.08 ' '3.94 '
 '4.37 ' '4.11 ' '4.05 ' '4.14 ' '3.83 ' '4.15 ' '4.09 ' '3.90 ' '3.82 '
 '3.63 ' '3.42 ' '3.40 ' '3.81 ' '4.12 ' '4.34 ' '3.20 ' '4.32 ' '4.28 '
 '2.0 ' '2.67 ' '3.25 ' '3.27 ' '2.33 ' '2.88 ' '2.80 ' '2.25 ' '4.10 '
 '4.24 ' '3.58 ' '3.13 ' '3.87 ' '2.75 ' '3.43 ']
['1' '3' '1.5' '2' '0' '2.5' '4' '4.5' '5.5' '6' 'Not specified' '3.5' '5'
 '6.5' '15.5']
['2' '1' 'Studio' '3' '4' '6' '5' '7' '15' '8' '9' '14']

In [139]:

# ---- RATING ----
# Remove 'No rating', strip spaces, and convert to float
airbnb_crime['rating'] = (
    airbnb_crime['rating']
    .replace('No rating', np.nan)   # drop invalid
    .str.strip()                    # remove trailing spaces
    .astype(float)                  # convert to float
)

# ---- BATHS ----
# Replace 'Not specified' with NaN and convert to float
airbnb_crime['baths'] = (
    airbnb_crime['baths']
    .replace('Not specified', np.nan)
    .astype(float)
)

# ---- BEDROOMS ----
# Replace 'Studio' with 0 and convert to float
airbnb_crime['bedrooms'] = (
    airbnb_crime['bedrooms']
    .replace('Studio', 0)
    .astype(int)
)

In [140]:
airbnb_crime.dtypes

id                                                         int64
neighbourhood_group                                       object
latitude                                                 float64
longitude                                                float64
room_type                                                 object
price                                                    float64
minimum_nights                                             int64
number_of_reviews                                          int64
last_review                                       datetime64[ns]
reviews_per_month                                        float64
calculated_host_listings_count                             int64
availability_365                                           int64
number_of_reviews_ltm                                      int64
rating                                                   float64
bedrooms                                                   int32
beds                                                       int64
baths                                                    float64
crime_count                                                int64
distance_to_statue_of_liberty                            float64
distance_to_times_square                                 float64
distance_to_central_park                                 float64
distance_to_empire_state_building                        float64
distance_to_brooklyn_bridge                              float64
distance_to_rockefeller_center                           float64
distance_to_one_world_trade_center                       float64
distance_to_broadway                                     float64
distance_to_grand_central_terminal                       float64
distance_to_the_metropolitan_museum_of_art               float64
distance_to_american_museum_of_natural_history           float64
distance_to_9/11_memorial_and_museum                     float64
distance_to_fifth_avenue                                 float64
distance_to_chrysler_building                            float64
distance_to_the_high_line                                float64
dtype: object

In [141]:
# Save the cleaned datasets to CSV files
airbnb_crime.to_csv('cleaned_airnb_crime.csv', index=False)